name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
           npm install @wdio/selenium-standalone-service --save-dev
           npm install @wdio/allure-reporter --save-dev
           npm install -g allure-commandline --save-dev

      - name: Run a multi-line script
        run: |
          npm run wdio
          npx allure generate [allure-results] && allure open
          
          
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir : ./docs
          enable_jekyll: true
